---
name: Linting
on:
  workflow_call:
jobs:
  pre-commit-ci:
    name: Pre-Commit
    runs-on: ubuntu-24.04
    env:
      PYTHON_VERSION: "3.12"
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
